name: Build Bulk Apply App

on:
  workflow_dispatch: # lets you trigger builds manually

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller selenium tk

      - name: Build app
        run: |
          pyinstaller --onefile --windowed bulk_apply_desktop_app.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bulk-apply-${{ matrix.os }}
          path: dist/*
